name: "🚀 Publish"

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: 🚀 Publish
        run: |
          npm install --package-lock-only &&
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
